# Generated by Django 5.2.13 on 2026-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (₸)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='В продаже')),
            ],
        ),
    ]
