# Generated by Django 5.2.13 on 2026-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, help_text='Формат: Название: Значение (каждое с новой строки)', null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Главное фото'),
        ),
    ]
