# Generated by Django 5.2.13 on 2026-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image_2_product_image_3_product_specs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Объем памяти')),
            ],
            options={
                'verbose_name': 'Объем памяти',
                'verbose_name_plural': 'Варианты памяти',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Базовая цена (₸)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, help_text='Формат: Название: Значение', null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='shop.color', verbose_name='Доступные цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_memory',
            field=models.ManyToManyField(blank=True, to='shop.memory', verbose_name='Доступные варианты памяти'),
        ),
    ]
